name: build multi-arch images

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule: [cron: "30 4 * * 1"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    continue-on-error: ${{ matrix.fail-ok }}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        platform: ["linux/amd64", "linux/arm64"]
        fail-ok: [false]
        include:
          [
            { platform: "linux/arm/v7", fail-ok: true },
            { platform: "linux/arm/v6", fail-ok: true },
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        if: ${{ runner.os == 'Linux' }}
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: "${{ matrix.platform }} build and push"
        continue-on-error: ${{ matrix.fail-ok }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./demo/Dockerfile
          tags: |
            ghcr.io/benleb/icecc-multiarch:latest
          platforms: ${{ matrix.platform }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        continue-on-error: ${{ matrix.fail-ok }}
